return {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
        no_italic = true,
        term_colors = true,
        transparent_background = false,
        styles = {
            comments = {},
            conditionals = {},
            loops = {},
            functions = {},
            keywords = {},
            strings = {},
            variables = {},
            numbers = {},
            booleans = {},
            properties = {},
            types = {},
        },
        color_overrides = {
            latte = {
                rosewater = "#f5e0dc",
                flamingo = "#f2cdcd",
                pink = "#f5c2e7",
                mauve = "#cba6f7",
                red = "#f38ba8",
                maroon = "#eba0ac",
                peach = "#fab387",
                yellow = "#f9e2af",
                green = "#a6e3a1",
                teal = "#94e2d5",
                sky = "#89dceb",
                sapphire = "#74c7ec",
                blue = "#89b4fa",
                lavender = "#b4befe",
                text = "#cdd6f4",
                subtext1 = "#bac2de",
                subtext0 = "#a6adc8",
                overlay2 = "#9399b2",
                overlay1 = "#7f849c",
                overlay0 = "#6c7086",
                surface2 = "#585b70",
                surface1 = "#45475a",
                surface0 = "#313244",
                base = "#000000",
                mantle = "#000000",
                crust = "#11111b",
            },
        },
        custom_highlights = function(C)
            return {
                NeoTreeWinSeparator = { fg = C.surface2 },
                TroubleNormal = { bg = C.base },
                BlinkCmpMenu = { bg = C.base },
                BlinkCmpDoc = { bg = C.base },
            }
        end,
        integrations = {
            telescope = {
                enabled = true,
                style = "nvchad",
            },
            dropbar = {
                enabled = true,
                color_mode = true,
            },
            aerial = true,
            alpha = true,
            bufferline = true,
            cmp = true,
            dashboard = true,
            flash = true,
            fzf = true,
            grug_far = true,
            gitsigns = true,
            harpoon = true,
            headlines = true,
            illuminate = true,
            indent_blankline = {
                enabled = true,
                colored_indent_levels = true,
                -- scope_color = "", -- catppuccin color (eg. `lavender`) Default: text
            },
            rainbow_delimiters = true,
            leap = true,
            lsp_trouble = true,
            mason = true,
            markdown = true,
            mini = true,
            native_lsp = {
                enabled = true,
                underlines = {
                    errors = { "undercurl" },
                    hints = { "undercurl" },
                    warnings = { "undercurl" },
                    information = { "undercurl" },
                },
            },
            navic = { enabled = true, custom_bg = "lualine" },
            neotest = true,
            neotree = true,
            noice = true,
            notify = true,
            semantic_tokens = true,
            snacks = true,
            treesitter = true,
            treesitter_context = true,
            which_key = true,
        },
    },
    specs = {
        {
            "akinsho/bufferline.nvim",
            optional = true,
            opts = function(_, opts)
                if (vim.g.colors_name or ""):find("catppuccin") then
                    opts.highlights = require("catppuccin.groups.integrations.bufferline").get()
                end
            end,
        },
    },
}
